### ISSUE TITLE
why did you perform bit reverse operation at the channel reliability (bhattacharyya) vector at PolarC?

### ISSUE THREAD

**Issue by JYFredPark** [tavildar/Polar#4]
and the code does not seem to work in BSC with all-zero message as an input

**Comment by tavildar** [comment]
The bit reverseal operator is described in the paper on polar codes. See section VII-B of https://arxiv.org/pdf/0807.3917.pdf 

I am not sure what changes you made to test code does not work for all zero-message as input. Please give more details.

**Comment by JYFredPark** [comment]
> The bit reverseal operator is described in the paper on polar codes. See section VII-B of https://arxiv.org/pdf/0807.3917.pdf
> 
> I am not sure what changes you made to test code does not work for all zero-message as input. Please give more details.

1. so for the bit reversal operation I found out that the operation was performed twice, one in choosing the best K(message length) channel and one in encoding where the link you uploaded indicates(section VII-B of https://arxiv.org/pdf/0807.3917.pdf)

2. For the BSC I just changed the parameters calculating bhattacharyya vectors and the channel itself. I am also running the code in higher rate (>0.9). So in this condition it seemed the code does not work but I found that I changed the value incorrectly and am trying the simulation turns out to be working out.

3. Your code generates random crc_matrix and it seems to work but why would be it?

**Comment by tavildar** [comment]
1. On bit reversal: yes, the channel selection has to match the encoder. Hence, bit reversal is applied in both places.
2. On BSC:  it is possible very high code rate may not work correctly due to limitations of polar code itself. Please make sure that the corresponding cross-over probability (parameter p) is low ( much less than (1 - 0.9)).
3. I don't think the original paper by Vardy et al specified a way of computing CRC -- most reasonable methods should work ok.
